stages:
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline-test
    env:
      PLUGIN_STORAGE_PATH: /var/lib/docker/1
- name: publishreal
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cmurpheus/pipeline-test
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
