stages:
- name: cat
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pipeline-test
    env:
      PLUGIN_STORAGE_PATH: /var/lib/docker/1
timeout: 60
notification: {}
